import { AppData } from './types';

export const INITIAL_APPS: AppData[] = [
  {
    id: '1',
    name: 'LuxFit AI Studio – Visual Studio',
    category: 'Tạo Ảnh',
    description: 'LuxFit AI Studio là một studio AI tất cả trong một giúp các thương hiệu hình ảnh hóa sản phẩm trong bối cảnh chuyên nghiệp.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCws4tbIsnKd_YviOLT9I5TH6p5vGwC7OmImlYWG1ySuB-xXoZ9ZrBzW2EXZfAtWN2_36qtjg6Y0gDka-u8IIOWFLdY5p3vDWro4KT3xrAxTO2f2e7oPdw58itjyih5HFUIUcCvgK6nJRXSz_tbjeZtUxACLn13OOSZrYTRb3B2rlYOSfZVxGZCdigBNBjAHGeWXai5t4XaKmnyyTHRdo96HIE7kgJSggifxH-i9Qnv4W4qzIEx4JpVCa2t6_gi2fULgmWPoYH8IJ8',
    accessLink: 'https://example.com/luxfit',
    purchaseDate: '2026-03-01',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
  {
    id: '2',
    name: 'Phòng Studio AI – Chuyên Nghiệp',
    category: 'Tạo Ảnh',
    description: 'Ứng dụng Studio AI chuyên nghiệp giúp bạn tạo và chỉnh sửa những bức ảnh chuyên nghiệp.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAV26ibZpO_VdJNXyeXAdx3XcjSOkTrvDaraSQvg4s4JfOJTlsyju2DzELSEV1Nyqssm8WERRRraw22mg1v55wSwF8reNwH0geWh4PmHadZVBL3VEZ-2fIP-KNFDRc2jfxVy8m1FujjFbdxC5OhQkreJqA1qkZwcW1MpC4eqD2ktnT5SQCnSm2RMlhmOhGxfegHH8qthrrACiPc3U5KUMIgvdIN0sEj_cClIc9EZbwTuXqPEew50eDmYKK3LfzxIyRo3z2RT4ORwWc',
    accessLink: 'https://example.com/studio',
    purchaseDate: '2026-02-28',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
  {
    id: '3',
    name: 'Lumina Fashion AI – Sáng Tạo',
    category: 'Tạo Ảnh',
    description: 'Lumina Fashion AI giúp các thương hiệu thời trang tạo ra hình ảnh ấn tượng và hiệu ứng ánh sáng sáng tạo.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBOlly3mZjZgsco6csyfGafJ6TvMq1Advb9yV8d14yJrK0tEbcbTBRCyJbG3jIiZO6dbeUz6VFf6z1G-73o7vDdy3z_EJ1z725CuKPD4PWYna1IkuJC0Mici8WXU0EhzsW3UCJ5Bc4y98NPKAoEAPrxz-fGK01Jz49YYF4qwAXXvBk-UnAkhVzI9wenef_ZI0x3L_dNyG8VSJ19MSeUxGJ3O-BquuzgdI_1wTuzsnG7kq0A0OX6LWagXczb_WxD97EQIysG3en8jWE',
    accessLink: 'https://example.com/lumina',
    purchaseDate: '2026-02-25',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
  {
    id: '4',
    name: 'WorldDress AI – Thử Đồ',
    category: 'Tạo Ảnh',
    description: 'WorldDress AI giúp bạn trải nghiệm các trang phục truyền thống của nhiều nền văn hóa khác nhau một cách mượt mà.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCGtRULv3A2uobvtGHEwfmLg82mhqWpALWcWN2ngmqEkkcaUx534UHUo5b50r2WQ8N3zMZRvvInAxkIOv2NqaJTn5H8Yhdo5zNTXRIg33kfCmLt4oZ6Bz2mcxYdV4UtaAMxQlEub3D_3Ae3tfRoI-U_W4vA-QL9Hew2qsgUrURFZ_Luga0j_StnwH9iHYXKgAx2YbbMGNSxNkiDVOGxwDI_3tGu9NcufFjhnvfs3UH4p4EmZ3em-5gR2KV_x3wqdBtjn_A-8b3qDAs',
    accessLink: 'https://example.com/worlddress',
    purchaseDate: '2026-02-20',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
  {
    id: '5',
    name: 'Vibe Banner Studio – Phiên bản Tết',
    category: 'Tạo Ảnh',
    description: 'Công cụ AI chuyên nghiệp giúp sao chép phong cách thiết kế cho banner, đặc biệt là cho dịp Tết.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDxQk0bhx3pZzh9jzXhJece1wgL-61O7MHMF90htClgpPTkNXAYld-fUw-Qtdy3HzFhFQICaTkLb2Ervz75WqJMItFO-kjJ3HH_DdN1MbtO9DlrwVMEHvJRxlafzOmieqPcFWGk5gfBd8LYx-hf74giGv8Mtc2MBX49paHLDGyOdI2B3aq5GCJr3VnMkv9xRaB3BFr27LOSkt7SbSHPdAB1nhTZ6EDYHt14IUd28IP_g1imhaZCEsPPEW3--yJPkd8-mm3PqlSSK80',
    accessLink: 'https://example.com/vibe',
    purchaseDate: '2026-02-15',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
  {
    id: '6',
    name: 'Họa Đồ Số – Biến Nội Dung',
    category: 'Tạo Ảnh',
    description: 'Họa Đồ Số là nền tảng AI chuyển đổi nội dung dài thành sơ đồ tư duy hoặc biểu đồ phức tạp.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC2Tbg6czyuXfYwueI4pAlD1sFkQo-y6kb2oVUn_8BQUG3EJ90iSbrw258EsLxVSycHyMTUG6HmWIE5b0zeIfswFU1PoUEBWsKf5sp1gzeZ9hfO50oNiIgcjOel6Kqw5TVkEh8-KyHd1BUWJ_xp_VKFPUJdX5Xe3NbTXtsiivmWDVXT51utl5Pmv4ja2AEQli2-O4TGsxlDK9dNeZjUlwdST0J7J6TxwTIxJfsSIEYvljn95I1-gk1-ZhRK8DpRQcY2KlK28bvc4o8',
    accessLink: 'https://example.com/hoadoso',
    purchaseDate: '2026-02-10',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
  {
    id: '7',
    name: 'AI Hairstylist – Thử Tóc',
    category: 'Tạo Ảnh',
    description: 'AI Hairstylist giúp bạn thử những kiểu tóc mới chỉ trong vài giây trước khi đến tiệm làm tóc.',
    thumbnailUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUUTyIYBAlus0nHX3aC6txEng44YJHMrAf5Yf8AnXp0GHDgG4Nk5U3JLeRWKE7ZcrC8ayH_16tM76aSVz71aGzCllTy2PJgvINZWyycYfw5Wx3Uga_Oo5OUPkPcx6EftrPKsEZP9wyrGD0NMRUsc1VTWiUZWxmO9YcdHcMB0bxSucAZ2ESBWDnoY6hYelrtFbPdVdEp-ABGtX4twxxrdHpcZx-QFOFu8Q8NvCW5eJFy9sf62ykXulbRRfyg8ollOkwHFN_9XYO_O8',
    accessLink: 'https://example.com/hairstylist',
    purchaseDate: '2026-02-05',
    licenseType: 'Trọn đời',
    isOwned: true,
  },
];
